### ISSUE TITLE
Is there any paper?

### ISSUE THREAD

**Issue by Grabber** [JohnTian/DepthImageUpsampling#1]
Is there any paper explaining the new depth upsampling method?

**Comment by Digital2Slave** [comment]
@Grabber Here is a version writen in Chinese.  [Depth upsampling algorithm based on image edge characteristics](http://www.joelcn.com/ch/reader/view_abstract.aspx?file_no=20141219&flag=1)
Or you will like to view the following papers which writen in English:
- Kim S Y, Ho Y S. Fast edge-preserving depth image upsampler [J]. IEEE Transactions on Consumer 
Electronics, 2012, 58(3):971-977. 
- Kai H L, Yu-chiang-frank W, Kai L H. Joint trilateral filtering for depth map super-resolution [C]. 
Visual Communications and Image Processing, Kuching, 2013.  
- Kang Y S, Lee S B, Ho Y S. Depth map upsampling using depth local features [J]. Electronics Letters, 
2014, 50(3):170-171. 
- Kim J. Joint-adaptive bilateral depth map upsampling [J]. Signal Processing: Image Communication, 
2014.  http://dx.doi.org/10.1016/j.image.2014.01.011.

**Comment by Juli-Freya** [comment]
An error occurred while the program was running. Is there a way to solve this problem？

Debug Assertion Failed
Program:C:\Windows\system32\MSVCP120D.dll
File:c:\program files(x86)\microsoft visual studio12.0\vc\include\xstring
Line:1168

Expression:invalid null pointer

**Comment by Digital2Slave** [comment]
@Juli-Freya 

Please check [Debug Assertion Failed! With Invalid null pointer error](https://stackoverflow.com/questions/24902778/debug-assertion-failed-with-invalid-null-pointer-error/24903368).

Note that:
>
- Please Check  the type of your program Win32 or X64,  run mode Release or Debug. 
- And make sure the OpenCV libs and dlls of Release and Debug are invoked correctly.
- **Do not debug your program in Release run mode!!!**

**Comment by Juli-Freya** [comment]
The type of my program is win32, run mode Debug. OpenCV libs and dlls are correctly.
I check the  link, still not solve the problem.

Debug my code step by step in Debug run mode , it failed in iosfwd

static size_t __CLRCALL_OR_CDECL length(const _Elem *_First)
		{	// find length of null-terminated string
		return (*_First == 0 ? 0
			: _CSTD strlen(_First));
		}

on screen:
Unhandled exception at 0x00908AD1 in TianSGU.exe: 0xC0000005: Access violation reading location 0x00000000.
Is there a way to solve this problem？

**Comment by Digital2Slave** [comment]
@Juli-Freya This issue is caused by invoke the `TianSGU.exe` incorrectly.  

I update the source code and README.md file.

```
Usage:
*.exe path_of_color_image path_of_disp_image scale_rate path_of_upsampling_image  path_of_badpixel_image
Example:
TianSGU.exe view1.png disp1.png 2 Tianout2.png Tianbad2.png
```
